using System;
using System.Collections.Generic;

namespace GxMcp.Worker.Helpers
{
    /// <summary>
    /// The WorkWithPlus generated-family naming convention.
    ///
    /// <para>
    /// <b>Why this exists.</b> Two places in the Worker need to recognise the objects a
    /// WorkWithPlus apply creates: the apply path, which reports
    /// <c>generatedObjects</c> and registers the new family in the search index, and the
    /// shadow-warning path, which maps a generated family member back to the
    /// PatternInstance host that owns it. Both previously hard-coded a
    /// <em>prefix</em> convention - <c>WW&lt;Trn&gt;</c>, <c>View&lt;Trn&gt;</c> -
    /// which no WorkWithPlus release actually produces.
    /// </para>
    ///
    /// <para>
    /// <b>What it really is.</b> A suffix convention. Applying WorkWithPlus to
    /// <c>Tbandad</c> produces <c>WorkWithPlusTbandad</c> (the host) plus
    /// <c>TbandadWW</c>, <c>TbandadWWDS</c>, <c>TbandadWWExport</c> and
    /// <c>TbandadWWGetFilterData</c> - observed directly in the KB of issue #359, where
    /// the same family also shows up as <c>tpaidadww</c>, <c>tferdadww</c>,
    /// <c>tmoedadww</c> and <c>tmsgdadww</c> on disk. So the host is a prefix and the
    /// family is a suffix, and the two have to be matched separately.
    /// </para>
    ///
    /// <para>
    /// <b>Consequence of getting this wrong.</b> It is silent, and it is total. A
    /// <c>WW&lt;Trn&gt;</c> probe does not find a wrong object, it finds nothing, so the
    /// apply reports only the host it created - <c>generatedObjects:
    /// ["WorkWithPlusTPacCls"]</c> - and, because the same lookup drives index
    /// registration, the four generated objects are never added to the search index
    /// either. They read back as <c>ObjectNotFound</c> until something else reindexes the
    /// KB. The apply itself genuinely succeeded; the report said otherwise.
    /// </para>
    ///
    /// <para>
    /// Both conventions are still probed. The suffix one is what current WorkWithPlus
    /// emits, but a KB generated by an older release may hold prefix-named objects, and
    /// a lookup that only knew the new shape would go blind on them.
    /// </para>
    /// </summary>
    internal static class WwpFamilyNaming
    {
        /// <summary>Prefix of the PatternInstance host. This one really is a prefix.</summary>
        internal const string HostPrefix = "WorkWithPlus";

        /// <summary>
        /// Family suffixes, longest first. Order matters for
        /// <see cref="TryGetBaseName"/>: <c>WWGetFilterData</c> and <c>WWExport</c> both
        /// begin with <c>WW</c>, so a shorter suffix tested first would strip
        /// <c>GetFilterData</c> off the base name and produce a host lookup for
        /// <c>TbandadGetFilterData</c>.
        /// </summary>
        private static readonly string[] FamilySuffixes =
        {
            "WWGetFilterData",
            "WWExport",
            "WWDS",
            "WW",
        };

        /// <summary>
        /// Family prefixes, longest first, for KBs generated by older WorkWithPlus
        /// releases. Same ordering rule as the suffixes.
        /// </summary>
        private static readonly string[] LegacyFamilyPrefixes =
        {
            "ExportReportWW",
            "ExportWW",
            "ViewWW",
            "View",
            "Prompt",
            "WW",
        };

        /// <summary>
        /// Every object name that could belong to <paramref name="baseName"/>'s generated
        /// family, host first.
        ///
        /// <para>
        /// The host leads deliberately: it is the one object whose existence proves the
        /// apply attached at all, so a caller reading the first entry can tell an
        /// attached apply from one that created nothing.
        /// </para>
        /// </summary>
        internal static IEnumerable<string> FamilyCandidates(string baseName)
        {
            if (string.IsNullOrEmpty(baseName)) yield break;

            yield return HostPrefix + baseName;

            foreach (var suffix in FamilySuffixes)
                yield return baseName + suffix;

            foreach (var prefix in LegacyFamilyPrefixes)
                yield return prefix + baseName;
        }

        /// <summary>
        /// The family-member names - excluding the host - that a complete apply is
        /// expected to have produced.
        ///
        /// <para>
        /// Used to report what is missing rather than to decide success. Whether every
        /// one of these is generated depends on the pattern version and the template, so
        /// this is a set to compare against, never a set that must all exist.
        /// </para>
        /// </summary>
        internal static IEnumerable<string> ExpectedFamilyNames(string baseName)
        {
            if (string.IsNullOrEmpty(baseName)) yield break;

            foreach (var suffix in FamilySuffixes)
                yield return baseName + suffix;
        }

        /// <summary>
        /// The base name of the Transaction a generated family member belongs to, or
        /// false when the name is not a family member.
        ///
        /// <para>
        /// This is the inverse of <see cref="FamilyCandidates"/> and it has to try both
        /// conventions, because the shadow warning fires on the generated object and
        /// nothing else about the name reveals which convention produced it.
        /// </para>
        /// </summary>
        internal static bool TryGetBaseName(string objectName, out string baseName)
        {
            baseName = null;
            if (string.IsNullOrEmpty(objectName)) return false;

            foreach (var suffix in FamilySuffixes)
            {
                if (!objectName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)) continue;
                baseName = objectName.Substring(0, objectName.Length - suffix.Length);
                return !string.IsNullOrEmpty(baseName);
            }

            foreach (var prefix in LegacyFamilyPrefixes)
            {
                if (!objectName.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) continue;
                baseName = objectName.Substring(prefix.Length);
                return !string.IsNullOrEmpty(baseName);
            }

            return false;
        }

        /// <summary>The PatternInstance host name for a parent object name.</summary>
        internal static string HostName(string baseName) => HostPrefix + baseName;
    }
}
