using System;
using System.Collections.Generic;
using System.Linq;
using GxMcp.Worker.Helpers;
using Xunit;

namespace GxMcp.Worker.Tests
{
    /// <summary>
    /// Issue #359: the WorkWithPlus generated family is named by SUFFIX, and two places
    /// in the Worker assumed PREFIX.
    ///
    /// <para>
    /// The apply reported <c>generatedObjects: ["WorkWithPlusTPacCls"]</c> and the four
    /// siblings read back as <c>ObjectNotFound</c>, because the lookup probed
    /// <c>WW&lt;Trn&gt;</c> / <c>ExportWW&lt;Trn&gt;</c> while WorkWithPlus generates
    /// <c>&lt;Trn&gt;WW</c> / <c>&lt;Trn&gt;WWExport</c>. The apply had worked; the
    /// report and the search index had not.
    /// </para>
    /// </summary>
    public class WwpFamilyNamingTests
    {
        // The names observed in the reporter's KB, from the issue itself.
        private const string Base = "Tbandad";

        [Fact]
        public void The_Observed_Suffix_Family_Is_Candidate_For_Every_Member()
        {
            var candidates = WwpFamilyNaming.FamilyCandidates(Base).ToList();

            foreach (var expected in new[]
            {
                "WorkWithPlusTbandad",
                "TbandadWW",
                "TbandadWWDS",
                "TbandadWWExport",
                "TbandadWWGetFilterData",
            })
                Assert.Contains(expected, candidates);
        }

        [Fact]
        public void The_Host_Is_Candidate_First()
        {
            // A caller reading the first entry must be able to tell an attached apply
            // from one that created nothing.
            Assert.Equal("WorkWithPlusTbandad",
                WwpFamilyNaming.FamilyCandidates(Base).First());
        }

        [Fact]
        public void The_Legacy_Prefix_Shapes_Are_Still_Candidates()
        {
            // A KB generated by an older release holds prefix-named objects, and a lookup
            // that only knew the new shape would go blind on them.
            var candidates = WwpFamilyNaming.FamilyCandidates(Base).ToList();

            Assert.Contains("WWTbandad", candidates);
            Assert.Contains("ViewTbandad", candidates);
            Assert.Contains("ExportWWTbandad", candidates);
        }

        [Fact]
        public void Every_Observed_Family_Member_Maps_Back_To_Its_Base()
        {
            foreach (var member in new[]
            {
                "TbandadWW", "TbandadWWDS", "TbandadWWExport",
                "TbandadWWGetFilterData", "WWTbandad", "ViewTbandad",
            })
            {
                Assert.True(WwpFamilyNaming.TryGetBaseName(member, out string baseName),
                    member + " did not resolve to a base name");
                Assert.Equal(Base, baseName);
            }
        }

        [Fact]
        public void The_Longest_Suffix_Wins_So_The_Base_Is_Not_Truncated()
        {
            // "WWGetFilterData" and "WWExport" both begin with "WW". Stripping "WW"
            // first would yield the base "TbandadGetFilterData" / "TbandadExport" and
            // then look for a host that does not exist - which is how a lookup that
            // "supports both conventions" still silently finds nothing.
            Assert.True(WwpFamilyNaming.TryGetBaseName("TbandadWWGetFilterData", out string a));
            Assert.Equal(Base, a);

            Assert.True(WwpFamilyNaming.TryGetBaseName("TbandadWWExport", out string b));
            Assert.Equal(Base, b);

            Assert.True(WwpFamilyNaming.TryGetBaseName("TbandadWWDS", out string c));
            Assert.Equal(Base, c);
        }

        [Fact]
        public void Resolution_Is_Case_Insensitive_And_Preserves_The_Callers_Casing()
        {
            // The generated .cs files are lowercase (tbandadww); KB object names are not
            // guaranteed to match case. The base is returned with the casing the caller
            // supplied rather than normalised, because it is fed straight into a
            // `WorkWithPlus<base>` host lookup and echoed in diagnostics.
            Assert.True(WwpFamilyNaming.TryGetBaseName("tbandadww", out string lower));
            Assert.Equal("tbandad", lower);

            Assert.True(WwpFamilyNaming.TryGetBaseName("TBANDADWWEXPORT", out string upper));
            Assert.Equal("TBANDAD", upper);
        }

        [Fact]
        public void An_Unrelated_Name_Resolves_To_No_Base()
        {
            // A false positive here would attribute an unrelated object to a pattern
            // host and warn the author that the IDE will overwrite their edits.
            //
            // Note that "WWAudit" is deliberately NOT here: it matches the legacy `WW`
            // prefix, so it resolves to "Audit". That ambiguity is inherent to the legacy
            // convention, which is why the suffix form is tried first and why the caller
            // confirms the host really is a WorkWithPlus object before attributing it.
            foreach (var name in new[] { "Tbandad", "MyTransaction", "WW", "", null })
                Assert.False(WwpFamilyNaming.TryGetBaseName(name, out _),
                    name + " should not resolve to a WorkWithPlus base name");
        }

        [Fact]
        public void A_Bare_Suffix_With_No_Base_Does_Not_Resolve()
        {
            Assert.False(WwpFamilyNaming.TryGetBaseName("WW", out _));
        }

        [Fact]
        public void The_Apply_Lookup_Probes_The_Suffix_Convention()
        {
            // The regression guard on the production wiring: the source must not carry a
            // hand-written prefix candidate list any more.
            string source = GxMcp.TestSupport.RepoSource.WithoutComments(
                "src", "GxMcp.Worker", "Services", "PatternApplyService.cs");

            Assert.Contains("WwpFamilyNaming.FamilyCandidates(baseName)", source, StringComparison.Ordinal);
            Assert.DoesNotContain("\"WW\" + baseName", source, StringComparison.Ordinal);
            Assert.DoesNotContain("\"ExportWW\" + baseName", source, StringComparison.Ordinal);
        }

        [Fact]
        public void The_Shadow_Warning_Lookup_Uses_The_Shared_Helper()
        {
            // The same wrong convention also meant the EditingWebFormUnderPattern warning
            // never fired on a real generated object: it stripped a prefix that a suffix-
            // named object does not have.
            string source = GxMcp.TestSupport.RepoSource.WithoutComments(
                "src", "GxMcp.Worker", "Services", "PatternAnalysisService.cs");

            Assert.Contains("WwpFamilyNaming.TryGetBaseName(obj.Name", source, StringComparison.Ordinal);
            Assert.DoesNotContain("candidatePrefixes", source, StringComparison.Ordinal);
            Assert.DoesNotContain("obj.Name.StartsWith(pre", source, StringComparison.Ordinal);
        }

        [Fact]
        public void The_Expected_Family_Excludes_The_Host()
        {
            // The host's existence proves the attach, not the generation, so counting it
            // as a generated family member would report a complete family on a failed
            // generation.
            var expected = WwpFamilyNaming.ExpectedFamilyNames(Base).ToList();

            Assert.DoesNotContain("WorkWithPlusTbandad", expected);
            Assert.Contains("TbandadWW", expected);
            Assert.Contains("TbandadWWExport", expected);
        }
    }
}
